# This file has been generated by node2nix 1.4.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "bluebird-3.5.0" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.5.0.tgz";
        sha1 = "791420d7f551eea2897453a8a77653f96606d67c";
      };
    };
    "body-parser-1.17.1" = {
      name = "body-parser";
      packageName = "body-parser";
      version = "1.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/body-parser/-/body-parser-1.17.1.tgz";
        sha1 = "75b3bc98ddd6e7e0d8ffe750dfaca5c66993fa47";
      };
    };
    "express-4.15.2" = {
      name = "express";
      packageName = "express";
      version = "4.15.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-4.15.2.tgz";
        sha1 = "af107fc148504457f2dca9a6f2571d7129b97b35";
      };
    };
    "morgan-1.8.1" = {
      name = "morgan";
      packageName = "morgan";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/morgan/-/morgan-1.8.1.tgz";
        sha1 = "f93023d3887bd27b78dfd6023cea7892ee27a4b1";
      };
    };
    "redis-2.7.1" = {
      name = "redis";
      packageName = "redis";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis/-/redis-2.7.1.tgz";
        sha1 = "7d56f7875b98b20410b71539f1d878ed58ebf46a";
      };
    };
    "require-dir-0.3.1" = {
      name = "require-dir";
      packageName = "require-dir";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-dir/-/require-dir-0.3.1.tgz";
        sha1 = "b5a8e28bae0343bb0d0cc38ab1f531e1931b264a";
      };
    };
    "supervisor-0.12.0" = {
      name = "supervisor";
      packageName = "supervisor";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supervisor/-/supervisor-0.12.0.tgz";
        sha1 = "de7e6337015b291851c10f3538c4a7f04917ecc1";
      };
    };
    "bytes-2.4.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-2.4.0.tgz";
        sha1 = "7d97196f9d5baf7f6935e25985549edd2a6c2339";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "1f4y61wc913jrnga7nny83gzf9l2488q6sl1ry9lbwgh5x5d3va0xcc0xrmjk6gdxl6d4r6rsk800xp5bazhjrx05yx1wpc8c8gg0w4";
      };
    };
    "debug-2.6.1" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.1.tgz";
        sha1 = "79855090ba2c4e3115cc7d8769491d58f0491351";
      };
    };
    "depd-1.1.1" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.1.tgz";
        sha1 = "5783b4e1c459f06fa5ca27f991f3d06e7a310359";
      };
    };
    "http-errors-1.6.2" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.6.2.tgz";
        sha1 = "0a002cc85707192a7e7946ceedc11155f60ec736";
      };
    };
    "iconv-lite-0.4.15" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.15.tgz";
        sha1 = "fe265a218ac6a57cfe854927e9d04c19825eddeb";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "qs-6.4.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.4.0.tgz";
        sha1 = "13e26d28ad6b0ffaa91312cd3bf708ed351e7233";
      };
    };
    "raw-body-2.2.0" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.2.0.tgz";
        sha1 = "994976cf6a5096a41162840492f0bdc5d6e7fb96";
      };
    };
    "type-is-1.6.15" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.15.tgz";
        sha1 = "cab10fb4909e441c82842eafe1ad646c81804410";
      };
    };
    "ms-0.7.2" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.2.tgz";
        sha1 = "ae25cf2512b3885a1d95d7f037868d8431124765";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "setprototypeof-1.0.3" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.0.3.tgz";
        sha1 = "66567e37043eeb4f04d91bd658c0cbefb55b8e04";
      };
    };
    "statuses-1.4.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.4.0.tgz";
        sha512 = "1xxwqpj713rq1idbmp7mj7cj9dl52lazgpd5x8a9g88jawbkn9xpwbgljl7cvnd0jqkll2zpdj5xy63dlis9l2k8vmx1n1gvyv8456f";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "mime-types-2.1.17" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.17.tgz";
        sha1 = "09d7a393f03e995a79f8af857b70a9e0ab16557a";
      };
    };
    "mime-db-1.30.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.30.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz";
        sha1 = "74c643da2dd9d6a45399963465b26d5ca7d71f01";
      };
    };
    "accepts-1.3.4" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.4.tgz";
        sha1 = "86246758c7dd6d21a6474ff084a4740ec05eb21f";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha1 = "9a5f699051b1e7073328f2a008968b64ea2955d2";
      };
    };
    "content-disposition-0.5.2" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.2.tgz";
        sha1 = "0cf68bb9ddf5f2be7961c3a85178cb85dba78cb4";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "encodeurl-1.0.1" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.1.tgz";
        sha1 = "79e3d58655346909fe6f0f45a5de68103b294d20";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "etag-1.8.1" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
        sha1 = "41ae2eeb65efa62268aebfea83ac7d79299b0887";
      };
    };
    "finalhandler-1.0.6" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-1.0.6.tgz";
        sha1 = "007aea33d1a4d3e42017f624848ad58d212f814f";
      };
    };
    "fresh-0.5.0" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.0.tgz";
        sha1 = "f474ca5e6a9246d6fd8e0953cfa9b9c805afa78e";
      };
    };
    "merge-descriptors-1.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz";
        sha1 = "b00aaa556dd8b44568150ec9d1b953f3f90cbb61";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "parseurl-1.3.2" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.2.tgz";
        sha1 = "fc289d4ed8993119460c156253262cdc8de65bf3";
      };
    };
    "path-to-regexp-0.1.7" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz";
        sha1 = "df604178005f522f15eb4490e7247a1bfaa67f8c";
      };
    };
    "proxy-addr-1.1.5" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.1.5.tgz";
        sha1 = "71c0ee3b102de3f202f3b64f608d173fcba1a918";
      };
    };
    "range-parser-1.2.0" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz";
        sha1 = "f49be6b487894ddc40dcc94a322f611092e00d5e";
      };
    };
    "send-0.15.1" = {
      name = "send";
      packageName = "send";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.15.1.tgz";
        sha1 = "8a02354c26e6f5cca700065f5f0cdeba90ec7b5f";
      };
    };
    "serve-static-1.12.1" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.12.1.tgz";
        sha1 = "7443a965e3ced647aceb5639fa06bf4d1bbe0039";
      };
    };
    "statuses-1.3.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.3.1.tgz";
        sha1 = "faf51b9eb74aaef3b3acf4ad5f61abf24cb7b93e";
      };
    };
    "utils-merge-1.0.0" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz";
        sha1 = "0294fb922bb9375153541c4f7096231f287c8af8";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha1 = "2299f02c6ded30d4a5961b0b9f74524a18f634fc";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "0q0fsr8bk1m83z0am0h2xn09vyfcf18adscxms8hclznwks1aihsisd96h8npx0idq5wwnypnqrkyk25m5d9zh3dk7rjs29nybc8bkc";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "forwarded-0.1.2" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.2.tgz";
        sha1 = "98c23dab1175657b8c0573e8ceccd91b0ff18c84";
      };
    };
    "ipaddr.js-1.4.0" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.4.0.tgz";
        sha1 = "296aca878a821816e5b85d0a285a99bcff4582f0";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "mime-1.3.4" = {
      name = "mime";
      packageName = "mime";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.3.4.tgz";
        sha1 = "115f9e3b6b3daf2959983cb38f149a2d40eb5d53";
      };
    };
    "basic-auth-1.1.0" = {
      name = "basic-auth";
      packageName = "basic-auth";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/basic-auth/-/basic-auth-1.1.0.tgz";
        sha1 = "45221ee429f7ee1e5035be3f51533f1cdfd29884";
      };
    };
    "on-headers-1.0.1" = {
      name = "on-headers";
      packageName = "on-headers";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-headers/-/on-headers-1.0.1.tgz";
        sha1 = "928f5d0f470d49342651ea6794b0857c100693f7";
      };
    };
    "double-ended-queue-2.1.0-0" = {
      name = "double-ended-queue";
      packageName = "double-ended-queue";
      version = "2.1.0-0";
      src = fetchurl {
        url = "https://registry.npmjs.org/double-ended-queue/-/double-ended-queue-2.1.0-0.tgz";
        sha1 = "103d3527fd31528f40188130c841efdd78264e5c";
      };
    };
    "redis-commands-1.3.1" = {
      name = "redis-commands";
      packageName = "redis-commands";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-commands/-/redis-commands-1.3.1.tgz";
        sha1 = "81d826f45fa9c8b2011f4cd7a0fe597d241d442b";
      };
    };
    "redis-parser-2.6.0" = {
      name = "redis-parser";
      packageName = "redis-parser";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-parser/-/redis-parser-2.6.0.tgz";
        sha1 = "52ed09dacac108f1a631c07e9b69941e7a19504b";
      };
    };
  };
  args = {
    name = "snippie-api";
    packageName = "snippie-api";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."bluebird-3.5.0"
      (sources."body-parser-1.17.1" // {
        dependencies = [
          sources."bytes-2.4.0"
          sources."content-type-1.0.4"
          (sources."debug-2.6.1" // {
            dependencies = [
              sources."ms-0.7.2"
            ];
          })
          sources."depd-1.1.1"
          (sources."http-errors-1.6.2" // {
            dependencies = [
              sources."inherits-2.0.3"
              sources."setprototypeof-1.0.3"
              sources."statuses-1.4.0"
            ];
          })
          sources."iconv-lite-0.4.15"
          (sources."on-finished-2.3.0" // {
            dependencies = [
              sources."ee-first-1.1.1"
            ];
          })
          sources."qs-6.4.0"
          (sources."raw-body-2.2.0" // {
            dependencies = [
              sources."unpipe-1.0.0"
            ];
          })
          (sources."type-is-1.6.15" // {
            dependencies = [
              sources."media-typer-0.3.0"
              (sources."mime-types-2.1.17" // {
                dependencies = [
                  sources."mime-db-1.30.0"
                ];
              })
            ];
          })
        ];
      })
      (sources."express-4.15.2" // {
        dependencies = [
          (sources."accepts-1.3.4" // {
            dependencies = [
              (sources."mime-types-2.1.17" // {
                dependencies = [
                  sources."mime-db-1.30.0"
                ];
              })
              sources."negotiator-0.6.1"
            ];
          })
          sources."array-flatten-1.1.1"
          sources."content-disposition-0.5.2"
          sources."content-type-1.0.4"
          sources."cookie-0.3.1"
          sources."cookie-signature-1.0.6"
          (sources."debug-2.6.1" // {
            dependencies = [
              sources."ms-0.7.2"
            ];
          })
          sources."depd-1.1.1"
          sources."encodeurl-1.0.1"
          sources."escape-html-1.0.3"
          sources."etag-1.8.1"
          (sources."finalhandler-1.0.6" // {
            dependencies = [
              (sources."debug-2.6.9" // {
                dependencies = [
                  sources."ms-2.0.0"
                ];
              })
              sources."unpipe-1.0.0"
            ];
          })
          sources."fresh-0.5.0"
          sources."merge-descriptors-1.0.1"
          sources."methods-1.1.2"
          (sources."on-finished-2.3.0" // {
            dependencies = [
              sources."ee-first-1.1.1"
            ];
          })
          sources."parseurl-1.3.2"
          sources."path-to-regexp-0.1.7"
          (sources."proxy-addr-1.1.5" // {
            dependencies = [
              sources."forwarded-0.1.2"
              sources."ipaddr.js-1.4.0"
            ];
          })
          sources."qs-6.4.0"
          sources."range-parser-1.2.0"
          (sources."send-0.15.1" // {
            dependencies = [
              sources."destroy-1.0.4"
              (sources."http-errors-1.6.2" // {
                dependencies = [
                  sources."inherits-2.0.3"
                ];
              })
              sources."mime-1.3.4"
              sources."ms-0.7.2"
            ];
          })
          sources."serve-static-1.12.1"
          sources."setprototypeof-1.0.3"
          sources."statuses-1.3.1"
          (sources."type-is-1.6.15" // {
            dependencies = [
              sources."media-typer-0.3.0"
              (sources."mime-types-2.1.17" // {
                dependencies = [
                  sources."mime-db-1.30.0"
                ];
              })
            ];
          })
          sources."utils-merge-1.0.0"
          sources."vary-1.1.2"
        ];
      })
      (sources."morgan-1.8.1" // {
        dependencies = [
          sources."basic-auth-1.1.0"
          (sources."debug-2.6.1" // {
            dependencies = [
              sources."ms-0.7.2"
            ];
          })
          sources."depd-1.1.1"
          (sources."on-finished-2.3.0" // {
            dependencies = [
              sources."ee-first-1.1.1"
            ];
          })
          sources."on-headers-1.0.1"
        ];
      })
      (sources."redis-2.7.1" // {
        dependencies = [
          sources."double-ended-queue-2.1.0-0"
          sources."redis-commands-1.3.1"
          sources."redis-parser-2.6.0"
        ];
      })
      sources."require-dir-0.3.1"
      sources."supervisor-0.12.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A simple REST API for storing text snippets by a key.";
      homepage = "https://github.com/Gerschtli/snippie-api#readme";
      license = "MIT";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}